env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
language: ruby
rvm:
  - 2.4.1
before_install: 
  - gem install bundler -v 2.0.1
  - bundle install
notifications:
  - false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rake db:setup
scripts:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rails test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT